In [2]:
#naložimo paket pandas
import pandas as pd
#razpredelnica indeksirana po id
potresi=pd.read_csv('potresi.csv', index_col='id')
#razpredelnica brez indeksiranja
potres=pd.read_csv('potresi.csv')
#omejitev razpredelnice (20 vrstic)
pd.options.display.max_rows=20

In [4]:
potresi

,leto,mesec,dan,ura,drzava,sirina,dolzina,globina,magnituda
id,,,,,,,,,
541962,2016,11,1,07:56:39,CENTRAL ITALY,43.00,13.16,10,4.9
541688,2016,10,31,16:02:43,OWEN FRACTURE ZONE REGION,20.85,61.73,10,5.5
541642,2016,10,31,13:44:00,CENTRAL IRAN,30.76,56.53,2,4.4
541620,2016,10,31,11:59:49,ROMANIA,45.87,26.78,90,4.0
541564,2016,10,31,09:38:13,BOSNIA AND HERZEGOVINA,43.26,17.88,8,4.2
541498,2016,10,31,07:05:45,CENTRAL ITALY,42.83,13.17,20,4.2
541428,2016,10,31,03:27:40,CENTRAL ITALY,42.77,13.09,11,4.3
541212,2016,10,30,18:21:09,CENTRAL ITALY,42.79,13.15,10,4.2
541060,2016,10,30,13:34:54,CENTRAL ITALY,42.80,13.17,9,4.6
540997,2016,10,30,12:07:00,CENTRAL ITALY,42.84,13.08,10,4.6
...,...,...,...,...,...,...,...,...,...
300710,2013,1,12,20:50:12,NEAR THE COAST OF WESTERN TURKEY,38.86,26.17,10,4.0
300613,2013,1,12,03:25:05,CENTRAL IRAN,31.93,51.07,9,5.3
300437,2013,1,11,00:30:20,AEGEAN SEA,39.67,25.52,25,4.3
300338,2013,1,10,05:50:00,AEGEAN SEA,39.68,25.54,10,4.0
300237,2013,1,9,15:41:33,AEGEAN SEA,39.71,25.63,9,4.6
300037,2013,1,8,14:16:08,AEGEAN SEA,39.66,25.54,10,5.7
299995,2013,1,8,06:15:04,CENTRAL TURKEY,37.92,37.96,15,4.4
299994,2013,1,8,06:05:07,CENTRAL TURKEY,37.93,37.96,14,4.6
299868,2013,1,7,04:20:24,FRANCE,44.76,6.75,2,4.1
299859,2013,1,7,00:41:56,STRAIT OF HORMUZ,26.76,56.22,10,4.4

In [5]:
potres

,id,leto,mesec,dan,ura,drzava,sirina,dolzina,globina,magnituda
0,541962,2016,11,1,07:56:39,CENTRAL ITALY,43.00,13.16,10,4.9
1,541688,2016,10,31,16:02:43,OWEN FRACTURE ZONE REGION,20.85,61.73,10,5.5
2,541642,2016,10,31,13:44:00,CENTRAL IRAN,30.76,56.53,2,4.4
3,541620,2016,10,31,11:59:49,ROMANIA,45.87,26.78,90,4.0
4,541564,2016,10,31,09:38:13,BOSNIA AND HERZEGOVINA,43.26,17.88,8,4.2
5,541498,2016,10,31,07:05:45,CENTRAL ITALY,42.83,13.17,20,4.2
6,541428,2016,10,31,03:27:40,CENTRAL ITALY,42.77,13.09,11,4.3
7,541212,2016,10,30,18:21:09,CENTRAL ITALY,42.79,13.15,10,4.2
8,541060,2016,10,30,13:34:54,CENTRAL ITALY,42.80,13.17,9,4.6
9,540997,2016,10,30,12:07:00,CENTRAL ITALY,42.84,13.08,10,4.6
...,...,...,...,...,...,...,...,...,...,...
3099,300710,2013,1,12,20:50:12,NEAR THE COAST OF WESTERN TURKEY,38.86,26.17,10,4.0
3100,300613,2013,1,12,03:25:05,CENTRAL IRAN,31.93,51.07,9,5.3
3101,300437,2013,1,11,00:30:20,AEGEAN SEA,39.67,25.52,25,4.3
3102,300338,2013,1,10,05:50:00,AEGEAN SEA,39.68,25.54,10,4.0
3103,300237,2013,1,9,15:41:33,AEGEAN SEA,39.71,25.63,9,4.6
3104,300037,2013,1,8,14:16:08,AEGEAN SEA,39.66,25.54,10,5.7
3105,299995,2013,1,8,06:15:04,CENTRAL TURKEY,37.92,37.96,15,4.4
3106,299994,2013,1,8,06:05:07,CENTRAL TURKEY,37.93,37.96,14,4.6
3107,299868,2013,1,7,04:20:24,FRANCE,44.76,6.75,2,4.1
3108,299859,2013,1,7,00:41:56,STRAIT OF HORMUZ,26.76,56.22,10,4.4

In [6]:
#prvih 10 vrstic v tabeli
potres.head(10)

,id,leto,mesec,dan,ura,drzava,sirina,dolzina,globina,magnituda
0,541962,2016,11,1,07:56:39,CENTRAL ITALY,43.00,13.16,10,4.9
1,541688,2016,10,31,16:02:43,OWEN FRACTURE ZONE REGION,20.85,61.73,10,5.5
2,541642,2016,10,31,13:44:00,CENTRAL IRAN,30.76,56.53,2,4.4
3,541620,2016,10,31,11:59:49,ROMANIA,45.87,26.78,90,4.0
4,541564,2016,10,31,09:38:13,BOSNIA AND HERZEGOVINA,43.26,17.88,8,4.2
5,541498,2016,10,31,07:05:45,CENTRAL ITALY,42.83,13.17,20,4.2
6,541428,2016,10,31,03:27:40,CENTRAL ITALY,42.77,13.09,11,4.3
7,541212,2016,10,30,18:21:09,CENTRAL ITALY,42.79,13.15,10,4.2
8,541060,2016,10,30,13:34:54,CENTRAL ITALY,42.80,13.17,9,4.6
9,540997,2016,10,30,12:07:00,CENTRAL ITALY,42.84,13.08,10,4.6

In [7]:
#zadnjih 10 vrstic v tabeli
potres.tail(10)

,id,leto,mesec,dan,ura,drzava,sirina,dolzina,globina,magnituda
3099,300710,2013,1,12,20:50:12,NEAR THE COAST OF WESTERN TURKEY,38.86,26.17,10,4.0
3100,300613,2013,1,12,03:25:05,CENTRAL IRAN,31.93,51.07,9,5.3
3101,300437,2013,1,11,00:30:20,AEGEAN SEA,39.67,25.52,25,4.3
3102,300338,2013,1,10,05:50:00,AEGEAN SEA,39.68,25.54,10,4.0
3103,300237,2013,1,9,15:41:33,AEGEAN SEA,39.71,25.63,9,4.6
3104,300037,2013,1,8,14:16:08,AEGEAN SEA,39.66,25.54,10,5.7
3105,299995,2013,1,8,06:15:04,CENTRAL TURKEY,37.92,37.96,15,4.4
3106,299994,2013,1,8,06:05:07,CENTRAL TURKEY,37.93,37.96,14,4.6
3107,299868,2013,1,7,04:20:24,FRANCE,44.76,6.75,2,4.1
3108,299859,2013,1,7,00:41:56,STRAIT OF HORMUZ,26.76,56.22,10,4.4

In [9]:
#posebni stolpec za uro
potres['ura']

0       07:56:39
1       16:02:43
2       13:44:00
3       11:59:49
4       09:38:13
5       07:05:45
6       03:27:40
7       18:21:09
8       13:34:54
9       12:07:00
          ...
3099    20:50:12
3100    03:25:05
3101    00:30:20
3102    05:50:00
3103    15:41:33
3104    14:16:08
3105    06:15:04
3106    06:05:07
3107    04:20:24
3108    00:41:56
Name: ura, dtype: object

In [10]:
#posebni stolpec za državo
potres['drzava']

0                          CENTRAL ITALY
1              OWEN FRACTURE ZONE REGION
2                           CENTRAL IRAN
3                                ROMANIA
4                 BOSNIA AND HERZEGOVINA
5                          CENTRAL ITALY
6                          CENTRAL ITALY
7                          CENTRAL ITALY
8                          CENTRAL ITALY
9                          CENTRAL ITALY
                      ...
3099    NEAR THE COAST OF WESTERN TURKEY
3100                        CENTRAL IRAN
3101                          AEGEAN SEA
3102                          AEGEAN SEA
3103                          AEGEAN SEA
3104                          AEGEAN SEA
3105                      CENTRAL TURKEY
3106                      CENTRAL TURKEY
3107                              FRANCE
3108                    STRAIT OF HORMUZ
Name: drzava, dtype: object

In [11]:
#posebni stolpec za globino
potres['globina']

0       10
1       10
2        2
3       90
4        8
5       20
6       11
7       10
8        9
9       10
        ..
3099    10
3100     9
3101    25
3102    10
3103     9
3104    10
3105    15
3106    14
3107     2
3108    10
Name: globina, dtype: int64

In [12]:
#posebni stolpec za magnitudo
potres['magnituda']

0       4.9
1       5.5
2       4.4
3       4.0
4       4.2
5       4.2
6       4.3
7       4.2
8       4.6
9       4.6
       ...
3099    4.0
3100    5.3
3101    4.3
3102    4.0
3103    4.6
3104    5.7
3105    4.4
3106    4.6
3107    4.1
3108    4.4
Name: magnituda, dtype: float64

In [13]:
#vrne dva stolpca - magnitudo in državo
potres[['magnituda','drzava']]

      magnituda                            drzava
0           4.9                     CENTRAL ITALY
1           5.5         OWEN FRACTURE ZONE REGION
2           4.4                      CENTRAL IRAN
3           4.0                           ROMANIA
4           4.2            BOSNIA AND HERZEGOVINA
5           4.2                     CENTRAL ITALY
6           4.3                     CENTRAL ITALY
7           4.2                     CENTRAL ITALY
8           4.6                     CENTRAL ITALY
9           4.6                     CENTRAL ITALY
...         ...                               ...
3099        4.0  NEAR THE COAST OF WESTERN TURKEY
3100        5.3                      CENTRAL IRAN
3101        4.3                        AEGEAN SEA
3102        4.0                        AEGEAN SEA
3103        4.6                        AEGEAN SEA
3104        5.7                        AEGEAN SEA
3105        4.4                    CENTRAL TURKEY
3106        4.6                    CENTRAL TURKEY
3107        4.1                            FRANCE
3108        4.4                  STRAIT OF HORMUZ

[3109 rows x 2 columns]

In [14]:
#vrne od 120 do 130 vrstice
potres[120:130]

,id,leto,mesec,dan,ura,drzava,sirina,dolzina,globina,magnituda
120,530086,2016,9,12,08:26:05,WESTERN TURKEY,38.90,27.74,14,4.8
121,529942,2016,9,11,13:10:07,FYR OF MACEDONIA,41.98,21.50,4,5.2
122,529883,2016,9,11,04:58:01,KOSOVO-SERBIA-FYROM BORDER REG.,42.00,21.51,4,4.2
123,529611,2016,9,9,17:24:20,"DODECANESE ISLANDS, GREECE",36.88,25.56,179,4.5
124,529391,2016,9,8,17:03:02,ROMANIA,45.67,26.53,140,4.1
125,529384,2016,9,8,15:31:07,GREECE,38.03,20.23,15,4.0
126,529324,2016,9,8,08:14:49,"AZORES ISLANDS, PORTUGAL",39.77,29.65,10,4.6
127,529261,2016,9,7,21:29:38,"CAUCASUS REGION, RUSSIA",41.82,46.56,50,4.3
128,529215,2016,9,7,16:57:48,"CAUCASUS REGION, RUSSIA",41.91,46.69,44,4.4
129,528915,2016,9,6,05:27:27,DODECANESE IS.-TURKEY BORDER REG,36.28,28.25,49,4.3

In [16]:
#vrne potres pod indeksom 125
potres.iloc[125]

id             529384
leto             2016
mesec               9
dan                 8
ura          15:31:07
drzava         GREECE
sirina          38.03
dolzina         20.23
globina            15
magnituda           4
Name: 125, dtype: object

In [17]:
#vrne tabelo s potresi, ki imajo magnitudo višjo ali enako od 6
potres[potres.magnituda>=6]

,id,leto,mesec,dan,ura,drzava,sirina,dolzina,globina,magnituda
21,540796,2016,10,30,06:40:18,CENTRAL ITALY,42.84,13.11,10,6.5
37,539727,2016,10,26,19:18:07,CENTRAL ITALY,42.92,13.13,8,6.1
167,525580,2016,8,24,01:36:32,CENTRAL ITALY,42.71,13.22,4,6.2
481,484213,2016,1,25,04:22:02,STRAIT OF GIBRALTAR,35.70,3.71,10,6.3
607,470390,2015,11,17,07:10:08,GREECE,38.76,20.45,10,6.5
971,436951,2015,4,16,18:07:44,"CRETE, GREECE",35.03,26.81,30,6.1
1768,395244,2014,8,18,02:32:05,IRAN-IRAQ BORDER REGION,32.58,47.62,10,6.2
1816,391719,2014,7,19,14:14:02,OWEN FRACTURE ZONE REGION,11.61,57.78,10,6.0
1959,379935,2014,5,24,09:25:02,AEGEAN SEA,40.29,25.40,27,6.9
2184,357329,2014,2,3,03:08:45,GREECE,38.26,20.32,2,6.0
2244,355461,2014,1,26,13:55:43,GREECE,38.19,20.41,18,6.1
2433,338758,2013,10,12,13:11:54,"CRETE, GREECE",35.56,23.31,47,6.4
2673,321766,2013,6,15,16:10:59,"CRETE, GREECE",34.23,25.00,10,6.2
2784,316362,2013,5,11,02:08:14,SOUTHERN IRAN,26.79,57.85,30,6.2
2867,312831,2013,4,16,10:44:20,IRAN-PAKISTAN BORDER REGION,28.14,62.08,87,7.8
2934,311828,2013,4,9,11:52:50,SOUTHERN IRAN,28.48,51.58,10,6.3

In [21]:
#magnitude razporejene od najmanjše do največje
potres.sort_values('magnituda')

,id,leto,mesec,dan,ura,drzava,sirina,dolzina,globina,magnituda
1554,401829,2014,9,28,08:22:17,EASTERN TURKEY,38.84,40.97,5,4.0
762,453704,2015,8,5,16:26:50,SPAIN,41.66,2.26,5,4.0
2522,331381,2013,8,25,01:18:14,AZERBAIJAN,41.64,46.43,2,4.0
2521,331414,2013,8,25,07:00:39,ICELAND REGION,62.90,25.18,10,4.0
2519,331791,2013,8,27,19:07:12,EASTERN IRAN,33.07,60.20,13,4.0
2516,331974,2013,8,29,04:06:17,ROMANIA,43.95,25.88,9,4.0
2511,332595,2013,9,2,12:36:35,PYRENEES,43.47,0.60,5,4.0
785,451768,2015,7,22,12:57:44,NORTHERN ITALY,44.16,10.89,10,4.0
789,450909,2015,7,16,13:19:00,EASTERN TURKEY,39.95,43.26,1,4.0
793,450552,2015,7,13,23:35:10,ROMANIA,45.66,26.44,148,4.0
...,...,...,...,...,...,...,...,...,...,...
167,525580,2016,8,24,01:36:32,CENTRAL ITALY,42.71,13.22,4,6.2
2784,316362,2013,5,11,02:08:14,SOUTHERN IRAN,26.79,57.85,30,6.2
1768,395244,2014,8,18,02:32:05,IRAN-IRAQ BORDER REGION,32.58,47.62,10,6.2
481,484213,2016,1,25,04:22:02,STRAIT OF GIBRALTAR,35.70,3.71,10,6.3
2934,311828,2013,4,9,11:52:50,SOUTHERN IRAN,28.48,51.58,10,6.3
2433,338758,2013,10,12,13:11:54,"CRETE, GREECE",35.56,23.31,47,6.4
21,540796,2016,10,30,06:40:18,CENTRAL ITALY,42.84,13.11,10,6.5
607,470390,2015,11,17,07:10:08,GREECE,38.76,20.45,10,6.5
1959,379935,2014,5,24,09:25:02,AEGEAN SEA,40.29,25.40,27,6.9
2867,312831,2013,4,16,10:44:20,IRAN-PAKISTAN BORDER REGION,28.14,62.08,87,7.8

In [23]:
#vrne tabelo urejeno padajoče po magnitudi in pri vsaki magnitudi še naraščajoče po letu
potres.sort_values(['magnituda','leto'], ascending=[False, True])

,id,leto,mesec,dan,ura,drzava,sirina,dolzina,globina,magnituda
2867,312831,2013,4,16,10:44:20,IRAN-PAKISTAN BORDER REGION,28.14,62.08,87,7.8
1959,379935,2014,5,24,09:25:02,AEGEAN SEA,40.29,25.40,27,6.9
607,470390,2015,11,17,07:10:08,GREECE,38.76,20.45,10,6.5
21,540796,2016,10,30,06:40:18,CENTRAL ITALY,42.84,13.11,10,6.5
2433,338758,2013,10,12,13:11:54,"CRETE, GREECE",35.56,23.31,47,6.4
2934,311828,2013,4,9,11:52:50,SOUTHERN IRAN,28.48,51.58,10,6.3
481,484213,2016,1,25,04:22:02,STRAIT OF GIBRALTAR,35.70,3.71,10,6.3
2673,321766,2013,6,15,16:10:59,"CRETE, GREECE",34.23,25.00,10,6.2
2784,316362,2013,5,11,02:08:14,SOUTHERN IRAN,26.79,57.85,30,6.2
1768,395244,2014,8,18,02:32:05,IRAN-IRAQ BORDER REGION,32.58,47.62,10,6.2
...,...,...,...,...,...,...,...,...,...,...
434,490196,2016,2,23,10:12:33,STRAIT OF GIBRALTAR,35.65,3.69,10,4.0
447,487863,2016,2,11,03:14:45,IRAN-IRAQ BORDER REGION,31.25,47.40,10,4.0
448,487695,2016,2,10,04:40:33,"AZORES ISLANDS, PORTUGAL",39.33,29.45,10,4.0
454,487025,2016,2,6,16:35:52,CENTRAL IRAN,34.64,51.48,16,4.0
457,486194,2016,2,2,14:21:15,CENTRAL TURKEY,38.85,37.82,5,4.0
458,486194,2016,2,2,14:21:15,CENTRAL TURKEY,38.85,37.82,5,4.0
465,484940,2016,1,27,21:57:48,STRAIT OF GIBRALTAR,35.52,3.75,10,4.0
486,483872,2016,1,23,04:00:44,WESTERN TURKEY,36.72,29.48,27,4.0
488,483717,2016,1,22,07:22:51,EASTERN TURKEY,39.27,40.16,14,4.0
503,484784,2016,1,13,15:24:57,GULF OF ADEN,13.08,50.24,10,4.0